
{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "snowalert.serviceAccountName" . }}
  labels:
    {{ include "snowalert.labels" . | nindent 4 }}
{{ end }}
